### ISSUE TITLE
Multiple Accounts Testing- TTS not working - (v1.0.0)

### ISSUE THREAD

**Issue by vladtepz** [keatontaylor/custom_components#86]
Started testing v1.0.0 with multiple accounts. Yay!

Everything looks good as far as setup. All 3 devices are shown and Online status & Sequence Commands seem to be working fine with my limited testing.

**TTS is not working. :(**

**Service used:** media_player.alexa_tts
**Service Data Used:** {"entity_id": "media_player.mike_jen_s_echo", "message": "Test message"}

No errors when calling the tts service, tested with debug logging for the component enabled.

I do get the following errors during the initial HA startup.

```
2019-02-23 10:42:25 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-23 10:42:25 WARNING (MainThread) [homeassistant.loader] You are using a custom component for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-23 10:42:27 WARNING (MainThread) [homeassistant.loader] You are using a custom component for hadockermon.switch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-23 10:42:33 WARNING (MainThread) [homeassistant.loader] You are using a custom component for alexa_media.media_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-23 10:42:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mike_jen_s_echo. Platform alexa_media does not generate unique IDs
2019-02-23 10:42:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mike_jen_s_echo. Platform alexa_media does not generate unique IDs
2019-02-23 10:42:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mikey_s_echo. Platform alexa_media does not generate unique IDs
2019-02-23 10:42:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mikey_s_echo. Platform alexa_media does not generate unique IDs
2019-02-23 10:42:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.nate_s_echo_dot. Platform alexa_media does not generate unique IDs
2019-02-23 10:42:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.nate_s_echo_dot. Platform alexa_media does not generate unique IDs
```

core.entity_registry has the following:

```
            {
                "config_entry_id": null,
                "device_id": null,
                "disabled_by": null,
                "entity_id": "media_player.mike_jen_s_echo",
                "name": null,
                "platform": "alexa_media",
                "unique_id": "XXXX"
            },
            {
                "config_entry_id": null,
                "device_id": null,
                "disabled_by": null,
                "entity_id": "media_player.mikey_s_echo",
                "name": null,
                "platform": "alexa_media",
                "unique_id": "XXXX"
            },
            {
                "config_entry_id": null,
                "device_id": null,
                "disabled_by": null,
                "entity_id": "media_player.nate_s_echo_dot",
                "name": null,
                "platform": "alexa_media",
                "unique_id": "XXXX"
            }
```
If you need any more info, I'm more then happy to provide it now that I can finally test it. :)

EDIT by alandtse: Scrubbed out the serial numbers.

**Comment by chali272** [comment]
i can also say that multiple account doesn't work,  even if i can get all devices to show up they only display status for one account, for exepel playing music on one device that belongs to one of the other account does not display, and you can't control it att al.  tts doesn't work on any account.

i tested using 3 accounts, 
a one more thing, "this device" shows up 3 time 

![screenshot 32](https://user-images.githubusercontent.com/11187523/53289876-5d39b680-379c-11e9-8b25-004ed88dd9c9.png)

Let me know if it's something you need from me.

//Regards

**Comment by alandtse** [comment]
Thanks @vladtepz @chali272 . I'm unable to test this since I only have the one account so I appreciate you offers to help.

Are the echos shared between the different accounts? What I think may be happening is that they're being discovered in each account and HA is probably spawning _2 and _3 entity_id versions of each (i.e. basically another one for each logged in account).  This is why your'e seeing `This Device` multiple times.  The component currently will use the specific account that is logged in to issue the command to the echo. This may result in the TTS failing if the account that is tied to the specific media_player entity_id doesn't have rights.

Please do the following:

1.  (Particularly once you start adding logs but for @vladtepz  specifically) Please scrub the serialNumber from your post as it may be sensitive info.
2. Check if there are duplicate entity ids (e.g., `media_player.mike_jen_s_echo_2` and `media_player.mike_jen_s_echo_3`) and then see if issuing TTS works for the variants.
3. Try [excluding_devices](https://github.com/keatontaylor/custom_components/wiki/Configuration#configuring-inclusions-or-exclusions-versions--096) that may be shared by the separate accounts where that account isn't the main owner/user.
4. We may need more debugging. Please add alexapy to your debugging. Please be careful about what you post publicly and be prepared to scrub.  Before you scrub, it will be helpful to review some of the data and let me know.  For example, this [page](https://alexa.amazon.com/api/bootstrap) will tell you the logged in accounts `customerId`. This [page](https://alexa.amazon.com/api/devices-v2/device) will let you know for each specific Alexa device, who the `deviceOwnerCustomerId` is.  In theory, the debugging commands we'll be using should pass data that matches.  If they don't, that may be what broke.

**Comment by vladtepz** [comment]
@alandtse

- The echo's are NOT shared and I was/am using `include_devices:` to exclude duplicates like "this device" from showing up. I have 3 devices with 3 separate entity_ids, i.e. none of them have the _2 and _3 appended.

**Configuration:**
```
alexa_media:
  accounts:
    - email: !secret alexa_mike_email
      password: !secret alexa_mike_password
      url: amazon.com
      include_devices:
        - "Mike & Jen's Echo"
    - email: !secret alexa_mikey_email
      password: !secret alexa_mikey_password
      url: amazon.com
      include_devices:
        - "Mikey's Echo"
    - email: !secret alexa_nate_email
      password: !secret alexa_nate_password
      url: amazon.com
      include_devices:
        - "Nate's Echo Dot"
```
Here is my Debug log.
**Debug Configuration:**
```
logger:
  default: error
  logs:
    custom_components.alexa_media: debug
    alexapy: debug
```

**Debug Log:**
```
2019-02-24 06:50:23 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-24 06:50:23 WARNING (MainThread) [homeassistant.loader] You are using a custom component for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-24 06:50:24 DEBUG (SyncWorker_14) [alexapy.alexalogin] Trying cookie from file /config/alexa_media.v******z@*****.com.pickle
2019-02-24 06:50:24 DEBUG (SyncWorker_14) [alexapy.alexalogin] cookie loaded: <RequestsCookieJar[*****]>
2019-02-24 06:50:25 DEBUG (SyncWorker_14) [alexapy.alexalogin] Logged in as v******z@*****.com
2019-02-24 06:50:25 DEBUG (SyncWorker_14) [alexapy.alexalogin] Using cookies to log in
2019-02-24 06:50:25 DEBUG (SyncWorker_14) [alexapy.alexalogin] Log in successful with cookies
2019-02-24 06:50:25 DEBUG (SyncWorker_14) [custom_components.alexa_media] Setting up Alexa devices
2019-02-24 06:50:25 DEBUG (SyncWorker_14) [alexapy.alexalogin] Trying cookie from file /config/alexa_media.m****************i@*****.com.pickle
2019-02-24 06:50:25 DEBUG (SyncWorker_14) [alexapy.alexalogin] cookie loaded: <RequestsCookieJar[*****]>
2019-02-24 06:50:25 DEBUG (SyncWorker_19) [custom_components.alexa_media] Updating devices for v******z@*****.com
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Logged in as m****************i@*****.com
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Using cookies to log in
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Log in successful with cookies
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [custom_components.alexa_media] Setting up Alexa devices
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Trying cookie from file /config/alexa_media.n************d@*****.com.pickle
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] cookie loaded: <RequestsCookieJar[*****]>
2019-02-24 06:50:26 DEBUG (SyncWorker_5) [custom_components.alexa_media] Updating devices for m****************i@*****.com
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Logged in as n************d@*****.com
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Using cookies to log in
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [alexapy.alexalogin] Log in successful with cookies
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [custom_components.alexa_media] Setting up Alexa devices
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [custom_components.alexa_media] Updating devices for n************d@*****.com
2019-02-24 06:50:26 DEBUG (SyncWorker_5) [custom_components.alexa_media] Found 3 devices, 1 bluetooth, last_called: {'serialNumber': '**************XH', 'timestamp': 1550972249219}
2019-02-24 06:50:26 DEBUG (SyncWorker_14) [custom_components.alexa_media] Found 3 devices, 1 bluetooth, last_called: {'serialNumber': '**************NB', 'timestamp': 1550974441106}
2019-02-24 06:50:27 DEBUG (SyncWorker_19) [custom_components.alexa_media] Found 4 devices, 1 bluetooth, last_called: {'serialNumber': '**************H4', 'timestamp': 1551006184958}
2019-02-24 06:50:31 DEBUG (SyncWorker_15) [custom_components.alexa_media.media_player] Refreshing Mike & Jen's Echo
2019-02-24 06:50:31 DEBUG (SyncWorker_4) [custom_components.alexa_media.media_player] Refreshing Mike & Jen's Echo
2019-02-24 06:50:31 DEBUG (SyncWorker_15) [custom_components.alexa_media.media_player] Refreshing Mikey's Echo
2019-02-24 06:50:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mike_jen_s_echo. Platform alexa_media does not generate unique IDs
2019-02-24 06:50:31 DEBUG (SyncWorker_16) [custom_components.alexa_media.media_player] Refreshing Mike & Jen's Echo
2019-02-24 06:50:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mike_jen_s_echo. Platform alexa_media does not generate unique IDs
2019-02-24 06:50:31 DEBUG (SyncWorker_4) [custom_components.alexa_media.media_player] Refreshing Mikey's Echo
2019-02-24 06:50:32 DEBUG (SyncWorker_15) [custom_components.alexa_media.media_player] Refreshing Nate's Echo Dot
2019-02-24 06:50:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mikey_s_echo. Platform alexa_media does not generate unique IDs
2019-02-24 06:50:32 DEBUG (SyncWorker_16) [custom_components.alexa_media.media_player] Refreshing Mikey's Echo
2019-02-24 06:50:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mikey_s_echo. Platform alexa_media does not generate unique IDs
2019-02-24 06:50:32 DEBUG (SyncWorker_16) [custom_components.alexa_media.media_player] Refreshing Nate's Echo Dot
2019-02-24 06:50:32 DEBUG (SyncWorker_4) [custom_components.alexa_media.media_player] Refreshing Nate's Echo Dot
2019-02-24 06:50:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.nate_s_echo_dot. Platform alexa_media does not generate unique IDs
2019-02-24 06:50:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.nate_s_echo_dot. Platform alexa_media does not generate unique IDs
2019-02-24 06:50:42 DEBUG (SyncWorker_18) [custom_components.alexa_media.media_player] Refreshing Mikey's Echo
2019-02-24 06:50:42 DEBUG (SyncWorker_18) [custom_components.alexa_media.media_player] Disabling polling and scheduling last update in 300 seconds for Mikey's Echo
2019-02-24 06:50:42 DEBUG (SyncWorker_2) [custom_components.alexa_media.media_player] Refreshing Nate's Echo Dot
2019-02-24 06:50:42 DEBUG (SyncWorker_2) [custom_components.alexa_media.media_player] Disabling polling and scheduling last update in 300 seconds for Nate's Echo Dot
2019-02-24 06:50:42 DEBUG (SyncWorker_16) [custom_components.alexa_media.media_player] Refreshing Mike & Jen's Echo
2019-02-24 06:50:42 DEBUG (SyncWorker_16) [custom_components.alexa_media.media_player] Disabling polling and scheduling last update in 300 seconds for Mike & Jen's Echo
2019-02-24 06:52:27 DEBUG (SyncWorker_17) [custom_components.alexa_media] Updating devices for v******z@*****.com
2019-02-24 06:52:27 DEBUG (SyncWorker_18) [custom_components.alexa_media] Updating devices for m****************i@*****.com
2019-02-24 06:52:27 DEBUG (SyncWorker_14) [custom_components.alexa_media] Updating devices for n************d@*****.com
2019-02-24 06:52:27 DEBUG (SyncWorker_14) [custom_components.alexa_media] Found 3 devices, 1 bluetooth, last_called: {'serialNumber': '**************NB', 'timestamp': 1550974441106}
2019-02-24 06:52:27 DEBUG (SyncWorker_18) [custom_components.alexa_media] Found 3 devices, 1 bluetooth, last_called: {'serialNumber': '**************XH', 'timestamp': 1550972249219}
2019-02-24 06:52:28 DEBUG (SyncWorker_17) [custom_components.alexa_media] Found 4 devices, 1 bluetooth, last_called: {'serialNumber': '**************H4', 'timestamp': 1551006184958}
```

**Notes:**
- This log was taken after trying to send a tts msg. It is missing the `DEBUG (SyncWorker_9) [alexapy.alexaapi] Running sequence: Alexa.Speak data: {*****` as if it's not being called. This message does show in the log, without the other errors, recreating the exact same steps if only 1 account is enabled.

- During initial setup, you cannot add all accounts at the same time, only the last account gets a config alert, you must setup each account separably, 1 at a time. _(i.e enable account 01 with account 02 & 03 disabled, enable account 02 with account 01 & 03 disable, etc... until you pull cookies for each account separately)_

-----

Doh!  For some reason I thought the "unique_id" was randomly generated, usually I'm more diligent at scrubbing my logs/info. :see_no_evil:

Just let me know if there is anything else I can do to help. Thanks! :smiley:

**Comment by alandtse** [comment]
Thanks. I may need more time to debug this, but some observations.

- The accounts apparently know about the other devices. At least they are showing at least 4 devices which could be Alexa mobile apps, but I can't tell from the output.  One way to check on your end is going to the devices end point. It may be worth verifying what devices show up in each account.
- Multiple echos may be showing up in more than one account since it's being added twice and failing; let me know the results of the bullet above if it is. This could also be because the include_devices is getting thrown by the apostrophes.
- I'll need to get you another build that gives better debug per account so I can tie the data to the account.  Right now I'm guessing since the hashed emails aren't tied to the debug output.

**Comment by alandtse** [comment]
Please try this [branch](https://github.com/alandtse/custom_components/tree/multiaccount_tts).  It has some more logging and a potential fix.

**Comment by chali272** [comment]
> Please try this [branch](https://github.com/alandtse/custom_components/tree/multiaccount_tts). It has some more logging and a potential fix.

hi, on hass.io using docker, tts works fine using 3 accounts with this branch, (nice work :-)  the only thing is during install, you have to add one account at the time or only the account in the botten show up,  after i added the 3 account i needed to do 2 restarts for music to be displayed for the first 2 accounts.  using tts at al 3 accounts at the same time works fine.  the volume control works but it bunches back to the previous state even that the volume increase/dicrest   (the volym change and stay at that point it's only the volym slider that bounces back)   //Regards

**Comment by alandtse** [comment]
I've pushed a new [version](https://github.com/alandtse/custom_components/tree/multiaccount_tts) that should fix the configurator bug.  Please test.

**Comment by vladtepz** [comment]
@alandtse Sorry, busy day yesterday, but finally had a chance to test out the "multiaccount_tts" branch this morning.

- Tested the configurator with all accounts enabled, it now worked as expected. 🎉 
- Tested TTS on all the accounts, and that too worked as expected. 🎉 

Awesome!!! 😃 

-----

FWIW, Still getting errors in my logs though. although it seems for only account 02 & 03 and not the first one I configured.

```
019-02-27 07:09:11 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mike_jen_s_echo. Platform alexa_media does not generate unique IDs
2019-02-27 07:09:11 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mike_jen_s_echo. Platform alexa_media does not generate unique IDs
2019-02-27 07:09:11 DEBUG (SyncWorker_9) [custom_components.alexa_media.media_player] m****************i@*****.com: Refreshing Mikey's Echo
2019-02-27 07:09:11 DEBUG (SyncWorker_10) [custom_components.alexa_media.media_player] m****************i@@*****.com: Refreshing Mikey's Echo
2019-02-27 07:09:11 DEBUG (SyncWorker_9) [custom_components.alexa_media.media_player] n************d@@*****.com: Refreshing Nate's Echo Dot
2019-02-27 07:09:11 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mikey_s_echo. Platform alexa_media does not generate unique IDs
2019-02-27 07:09:11 DEBUG (SyncWorker_13) [custom_components.alexa_media.media_player] m****************i@*****.com: Refreshing Mikey's Echo
2019-02-27 07:09:11 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.mikey_s_echo. Platform alexa_media does not generate unique IDs
2019-02-27 07:09:12 DEBUG (SyncWorker_10) [custom_components.alexa_media.media_player] n************d@*****.com: Refreshing Nate's Echo Dot
2019-02-27 07:09:12 DEBUG (SyncWorker_13) [custom_components.alexa_media.media_player] n************d@*****.com: Refreshing Nate's Echo Dot
2019-02-27 07:09:12 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.nate_s_echo_dot. Platform alexa_media does not generate unique IDs
2019-02-27 07:09:12 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.nate_s_echo_dot. Platform alexa_media does not generate unique IDs
```
-----

**Here is the extra logging:**
```
n019-02-27 07:25:21 DEBUG (SyncWorker_19) [custom_components.alexa_media] n************d@*****.com: Found 3 devices, 1 bluetooth, last_called: {'serialNumber': 'G************3NB', 'timestamp': 1551269696325}
2019-02-27 07:25:21 DEBUG (SyncWorker_19) [custom_components.alexa_media] n************d@*****.com: Adding 0 items; forced inc: ['This Device', "Nathan's Alexa Apps"] exc: []
2019-02-27 07:25:21 DEBUG (SyncWorker_5) [custom_components.alexa_media] m****************i@*****.com: Found 3 devices, 1 bluetooth, last_called: {'serialNumber': '9************BXH', 'timestamp': 1551196212891}
2019-02-27 07:25:21 DEBUG (SyncWorker_5) [custom_components.alexa_media] m****************i@*****.com: Adding 0 items; forced inc: ['This Device', "Mike's Alexa Apps"] exc: []
2019-02-27 07:25:22 DEBUG (SyncWorker_3) [custom_components.alexa_media] v******z@*****.com: Found 4 devices, 1 bluetooth, last_called: {'serialNumber': '9************XH4', 'timestamp': 1551269638370}
2019-02-27 07:25:22 DEBUG (SyncWorker_3) [custom_components.alexa_media] v******z@*****l.com: Adding 0 items; forced inc: ["Jennifer's Alexa Apps", 'This Device', "Michael's Alexa Apps"] exc: []
```
-----

And just a little extra info about my specific setup for good measure.

- I have x3 separate accounts
- Wife & my accounts are linked/shared, using only my email to login.
- The other x2 accounts are NOT shared/connected to any other accounts.

**Account 01 Devices:** ( Wife & I )
- "Mike & Jen's Echo" - _( Main Amazon Echo )_
- "Jennifer's Alexa Apps" - _( Wife's Mobile App )_
- "Michael's Alexa Apps" - _( My Mobile App )_
- "This Device" - _( Assuming THIS alexa HA instance )_

**Account 02 Devices:**
- "Mikey's Echo" - _( Account 02, Echo Dot )_
- "Mike's Alexa Apps" - _( Account 02 Mobile App )_
- "This Device" - _( Assuming THIS alexa HA instance )_

**Account 03 Devices:**
- "Nate's Echo Dot" - _( Account 03, Echo Dot )_
- "Nathan's Alexa Apps" - _( Account 03 Mobile App )_
- "This Device" - _( Assuming THIS alexa HA instance )_

-----

Been looking forward to this update since you first released it as a docker/hassio addon, many moons ago. 😄  I've been currently using my own custom modified `alexa_remote_control` & `alexa_wrapper` scripts so I look forward to being able to migrate my setup to this. 🎉 

Just let me know if there is anything else I can do to help. Thanks! 😃

**Comment by alandtse** [comment]
Thanks for the detailed logs. I figured out the issue. The checks to ensure we weren't double adding devices was broken.  Please try the latest version #100.
